DRAFT: V0.2.0
Elderjs/elderjs pull request #35
Opened 2020-09-14 17:07 UTC by nickreese

2020-09-16 22:21 UTC, sw-yx commented
yay v1

2020-09-16 22:56 UTC, nickreese commented
@halafi Can you figure out why these build tests are failing? They are overwriting the `process.env` and causing issues.

Besides that all the tests should be working and just need to get it working on EG and others.

2020-09-17 08:21 UTC, halafi commented on src/__tests__/__snapshots__/externalHelpers.spec.ts.snap
> +exports[`#externalHelpers works - buildHelpers 1`] = `undefined`;
this broke the test

2020-09-17 08:34 UTC, halafi requested changes
From general check / CR it looks good, but we should write tests for the new files:

- [ ] prepareShortcodeParser.ts
- [ ] getRollupConfig.ts
- [ ] shortcodes.ts

happy to help if you need me to, pipeline should be passing now

2020-09-17 16:17 UTC, nickreese commented
@halafi we will also need a test for the new helper function in `prepareInlineShortcode.ts` basically in svelte templates shortcodes are a little silly to have. 

Test:
- [ ] prepareInlineShortcode

By adding `@html helpers.shortcode({name:'foo' props: {key: 'val'}, content: 'string'});` we can inline them predictably, handle the JSON stringify, etc.

2020-09-18 20:26 UTC, nickreese commented
TODO:

- [ ] test the hydration options.

2020-09-21 23:07 UTC, nickreese commented
@halafi Moved the majority of the server implementation to a hook so it can easily be overwritten, customized, or whatever users want to do. Tests there are failing :/

2020-09-22 11:58 UTC, halafi commented on src/hooks.ts
> +        let route = routes[requestObject.route];
@nickreese  if we do not have `requestObject` then this will throw `TypeError` (trying to access route on undefined), and we check for requestObject in the next if block

2020-09-22 18:26 UTC, merged